- name: "Configure device-search 'option' element nodes in '{{ syncthing_user_config_file_path }}'"
  community.general.xml:
    path: "{{ syncthing_user_config_file_path }}"
    xpath: "/configuration/options/{{ item.name }}"
    value: "{{ item.val }}"
    pretty_print: true
  become: true
  become_user: "{{ syncthing_user_name }}"
  loop:
    - name: 'globalAnnounceEnabled'
      val: "{{ syncthing_search_for_devices_on_public_lookup_server }}"
      descrip: 'search for devices on public lookup server'
    - name: 'globalAnnounceServer'
      val: "{{ syncthing_public_lookup_server_address }}"
      descrip: 'public lookup server address'
    - name: 'localAnnounceEnabled'
      val: "{{ syncthing_search_for_devices_on_local_lan }}"
      descrip: 'search for devices on local LAN'
    - name: 'relaysEnabled'
      val: "{{ syncthing_use_device_relay_connections }}"
      descrip: 'use device relay connections'
    - name: 'relayReconnectIntervalM'
      val: "{{ syncthing_relay_connect_interval_minutes }}"
      descrip: 'device relay connect interval, in minutes'

