- name: "Create zipped folders list"
  set_fact:
    zipped_folders: "{{ zipped_folders | default([]) + [item | combine(id_filter)] }}"
  loop: "{{ syncthing_list_of_available_sync_folders }}"
  vars:
    id_filter: "{{ syncthing_list_of_local_folders_to_sync | selectattr('folder_id', '==', item.folder_id) | first }}"

- name: "Test out zipping folders list"
  ansible.builtin.debug:
    msg:
      - "Zipped folders list: {{ zipped_folders }}"

- name: "Set all syncthing settings in '{{ syncthing_user_config_file_path }}'"
  ansible.builtin.template:
    dest: "{{ syncthing_user_config_file_path }}"
    src: "config_xml.j2"
    force: true
  become: true
  become_user: "{{ syncthing_user_name }}"

