- name: "Configure attributes for 'gui' element in '{{ syncthing_user_config_file_path }}'"
  community.general.xml:
    path: "{{ syncthing_user_config_file_path }}"
    xpath: /configuration/gui
    attribute: "{{ gui_attrib.name }}"
    value: "{{ gui_attrib.val }}"
  become: true
  become_user: "{{ syncthing_user_name }}"
  loop:
    - { name: 'enabled', val: "{{ syncthing_enable_web_ui_access }}", descrip: 'allow web UI access' }
    - { name: 'tls', val: "{{ syncthing_redirect_web_ui_to_https }}", descrip: 'redirect web UI http to https' }
    - { name: 'debugging', val: "{{ syncthing_enable_rest_api_debug_endpoints }}", descrip: 'enable REST API debug endpoints' }
  loop_control:
    loop_var: gui_attrib

- name: "Configure nodes for 'gui' element in '{{ syncthing_user_config_file_path }}'"
  community.general.xml:
    path: "{{ syncthing_user_config_file_path }}"
    xpath: "/configuration/gui/{{ gui_element.name }}"
    value: "{{ gui_element.val }}"
  become: true
  become_user: "{{ syncthing_user_name }}"
  loop:
    - { name: 'address', val: "{{ syncthing_web_ui_address }}", descrip: 'web UI URL address' }
    - { name: 'insecureAdminAccess', val: "{{ syncthing_enable_non_local_host_web_ui_login }}", descrip: 'enable non-local-host web UI login' }
    - { name: 'sendBasicAuthPrompt', val: "{{ syncthing_prompt_for_username_and_passwd }}", descrip: 'prompt for user-name and password' }
  loop_control:
    loop_var: gui_element

