- name: "Stop 'syncthing' service, prior to editing config file"
  ansible.builtin.service:
    name: syncthing
    state: stopped
    enabled: true
  changed_when: false
  become: true
  become_user: root

