# Main Config Ref:
# --> https://docs.syncthing.net/users/config.html

- name: "Create config_folders: add common fields to syncthing_list_of_local_folders_to_sync"
  set_fact:
    config_folders: "{{ config_folders | default([]) + [item | combine(id_filter)] }}"
  loop: "{{ syncthing_list_of_available_sync_folders }}"
  vars:
    local_folders_list: "{{ syncthing_list_of_local_folders_to_sync }}"
    id_filter: "{{ local_folders_list | selectattr('folder_id', '==', item.folder_id) | first }}"

- name: "Write all syncthing settings to '{{ syncthing_user_settings_file_path }}'"
  ansible.builtin.template:
    dest: "{{ syncthing_user_settings_file_path }}"
    src: "config_xml.j2"
    force: true
  become: true
  become_user: "{{ syncthing_user_name }}"

