- name: "Start 'syncthing' service, and enable it to start on boot"
  ansible.builtin.service:
    name: syncthing
    state: started
    enabled: true
  changed_when: false
  become: true
  become_user: root

