- name: "Start 'syncthing' service, and enable it to start on boot"
  ansible.builtin.service:
    name: syncthing
    state: started
  changed_when: false
  become: true
  become_user: root

- name: "Enable 'syncthing' service to start on boot"
  ansible.builtin.service:
    name: syncthing
    enabled: true
  become: true
  become_user: root

