- name: "Check user-provided syncthing config vars"
  ansible.builtin.include_tasks: check_config/main.yml

- name: "Stop syncthing service, prior to config tasks"
  ansible.builtin.include_tasks: stop_service/main.yml

- name: "Configure OS-specific syncthing service files"
  ansible.builtin.include_tasks: config_service/main.yml

- name: "Create syncthing user config and logging directories"
  ansible.builtin.include_tasks: create_dirs/main.yml

- name: "Set user-provided private, public keys in syncthing key files"
  ansible.builtin.include_tasks: set_keys/main.yml

- name: "Write all syncthing settings to the settings file"
  ansible.builtin.include_tasks: write_settings/main.yml

- name: "Start and enable syncthing service"
  ansible.builtin.include_tasks: start_service/main.yml

