- name: "Stop any running syncthing service"
  ansible.builtin.include_tasks: stop_service/main.yml

- name: "Create syncthing user config dir"
  ansible.builtin.include_tasks: config_dir/main.yml

- name: "Set user-provided private, public keys in syncthing key files"
  ansible.builtin.include_tasks: set_keys/main.yml

- name: "Configure all syncthing settings"
  ansible.builtin.include_tasks: settings/main.yml

- name: "Start and enable syncthing service"
  ansible.builtin.include_tasks: start_service/main.yml

