- name: "Stop any running syncthing service"
  ansible.builtin.include_tasks: stop_service/main.yml

- name: "Set user-provided private, public keys in syncthing key files"
  ansible.builtin.include_tasks: set_keys/main.yml

- name: "Generate syncthing config file, if not exist"
  ansible.builtin.include_tasks: gen_config/main.yml

- name: "Configure all syncthing settings"
  ansible.builtin.include_tasks: settings/main.yml

- name: "Start and enable syncthing service"
  ansible.builtin.include_tasks: start_service/main.yml

