- name: "Check each folder in syncthing_list_of_local_folders_to_sync is in syncthing_list_of_available_sync_folders"
  ansible.builtin.assert:
    that: "{{ local_folder in common_folders_list }}"
    fail_msg: "local folder '{{ local_folder }}' not found in '{{ common_folders_list }}'"
    quiet: true
  loop: "{{ syncthing_list_of_local_folders_to_sync | map(attribute='folder_id') | list }}"
  loop_control:
    loop_var: local_folder
  vars:
    common_folders_list: "{{ syncthing_list_of_available_sync_folders | map(attribute='folder_id') | list }}"

